### ISSUE TITLE
Build image on release

### ISSUE THREAD

**Issue by AdrianDAlessandro** [AdrianDAlessandro/rse-competencies-toolkit-webapp#14]
Following from #9 a release workflow should be added so that the docker image is built and deployed to the GitHub container registry on release.

This will be something like this:

```yaml
on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  publish:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and push Docker image for the web app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
```
